if (!("readxl") %in% installed.packages()) install.packages("readxl")
if (!("ggplot2") %in% installed.packages()) install.packages("ggplot2")
library(ggplot2)
library(readxl)
covid_19_bauru_mortes <- read_excel("Documents\UNESP\IEAD-2022\covid-19-bauru-joao-pedro-bueno\dados\covid_19_bauru_mortes.xlsx", range=cell_cols("G:G"), col_types=c("date"))
datas_obito <- table(covid_19_bauru_mortes)
barplot(datas_obito[-1])
mtext(side = 1, text = "Data ocorrida", line = 2)
mtext(side = 2, text = "Nº de mortes", line = 2)